baseurl = "https://example.org/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "Creative portfolio"
[params]
copyright = "&copy;2016 Your name or company"
description = "Describe your website"
email = "you@yoursite.com"
sidebarabout = ["I am a creative illustrator and graphic designer with more than 10 years of experience.", "Originally from Toronto, currently based in London."]
style = "blue"
[params.social]
email = "email@example.com"
facebook = "full page or profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
linkedin = "full profile url in linkedin"
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
