baseurl = "https://www.sappayabatra.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "สัปปายะบาตร"
[params]
copyright = "&copy;2018 SappayaBatra"
description = ""
email = "info@sappayabatra.com"
sidebarabout = ["I am a creative illustrator and graphic designer with more than 10 years of experience.", "Originally from Toronto, currently based in London."]
style = "blue"
[params.social]
email = "info@sappayabatra.com"
facebook = "full page or profile url in facebook"
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
